# Color constants for current assessment areas

AR_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "GN"]
AR_COLOR_2 = ALL_FI_COLORS[FISHERY_CODE == "LLF"]
AR_COLOR_3 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
AR_COLOR_0 = ALL_FI_COLORS[FISHERY_CODE == "BB"]

AR_COLORS = AR_COLOR_1
AR_COLORS = rbind(AR_COLORS, AR_COLOR_2)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_3)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_0)

# Color constants for original areas

DARKEN_AMOUNT = 0.05

BB  = ALL_FI_COLORS[FISHERY_CODE == "BB"]
PSLS= ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
GN  = ALL_FI_COLORS[FISHERY_CODE == "GN"]
LLF = ALL_FI_COLORS[FISHERY_CODE == "LLF"]

BB_1 = BB
BB_1$FILL    = darken(BB_1$FILL,    amount = DARKEN_AMOUNT)
BB_1$OUTLINE = darken(BB_1$OUTLINE, amount = DARKEN_AMOUNT)

BB_2 = BB_1
BB_2$FILL    = darken(BB_2$FILL,    amount = DARKEN_AMOUNT)
BB_2$OUTLINE = darken(BB_2$OUTLINE, amount = DARKEN_AMOUNT)

BB_3 = BB_2
BB_3$FILL    = darken(BB_3$FILL,    amount = DARKEN_AMOUNT)
BB_3$OUTLINE = darken(BB_3$OUTLINE, amount = DARKEN_AMOUNT)

BB_4 = BB_3
BB_4$FILL    = darken(BB_4$FILL,    amount = DARKEN_AMOUNT)
BB_4$OUTLINE = darken(BB_4$OUTLINE, amount = DARKEN_AMOUNT)

PSLS_1 = PSLS
PSLS_1$FILL = darken(PSLS_1$FILL,       amount = DARKEN_AMOUNT)
PSLS_1$OUTLINE = darken(PSLS_1$OUTLINE, amount = DARKEN_AMOUNT)

PSLS_2 = PSLS_1
PSLS_2$FILL = darken(PSLS_2$FILL,       amount = DARKEN_AMOUNT)
PSLS_2$OUTLINE = darken(PSLS_2$OUTLINE, amount = DARKEN_AMOUNT)

AR_ORIG_COLORS = BB
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, BB_1)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, GN)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, LLF)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, PSLS)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, PSLS_1)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, PSLS_2)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, BB_2)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, BB_3)
AR_ORIG_COLORS = rbind(AR_ORIG_COLORS, BB_4)

# Color constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "BB"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LIT"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])

# Color constants for current fisheries

FI_COLOR_PSFS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FI_COLOR_PSLS = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
FI_COLOR_LL   = ALL_FI_COLORS[FISHERY_CODE == "LLD"][, FISHERY_CODE := "LL"]
FI_COLOR_FL   = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "FL"]
FI_COLOR_BB   = ALL_FI_COLORS[FISHERY_CODE == "BB"]
FI_COLOR_LINE = ALL_FI_COLORS[FISHERY_CODE == "LIT"][, FISHERY_CODE := "LINE"]
FI_COLOR_OTHER= ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OTHER"]

FI_COLORS = FI_COLOR_PSFS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PSLS)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_FL)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_BB)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LINE)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OTHER)