# Colour constants for current assessment areas

AR_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "LLF"]  # IRYFT1A
AR_COLOR_2 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"] # IRYFT1B
AR_COLOR_3 = ALL_FI_COLORS[FISHERY_CODE == "BB"]   # IRYFT02
AR_COLOR_4 = ALL_FI_COLORS[FISHERY_CODE == "GN"]   # IRYFT03
AR_COLOR_5 = ALL_FI_COLORS[FISHERY_CODE == "LIT"]  # IRYFT04
AR_COLOR_0 = ALL_FI_COLORS[FISHERY_CODE == "OT"]   # ...

AR_COLORS = AR_COLOR_1
AR_COLORS = rbind(AR_COLORS, AR_COLOR_2)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_3)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_4)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_5)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_0)

# Colour constants for original areas

AR_ORIG_COLORS = AR_COLORS

# Colour constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]                  # FS + LS
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"]) # LL + FL
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "BB"])  # BB 
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "GN"])  # GN
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LIT"]) # HD + TR
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])  # OT

# Colour constants for current fisheries

FI_COLOR_FS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"][, FISHERY_CODE := "FS"]
FI_COLOR_LS = ALL_FI_COLORS[FISHERY_CODE == "PSLS"][, FISHERY_CODE := "LS"]
FI_COLOR_LL = ALL_FI_COLORS[FISHERY_CODE == "LLD"][,  FISHERY_CODE := "LL"]
FI_COLOR_LF = ALL_FI_COLORS[FISHERY_CODE == "LLF"][,  FISHERY_CODE := "LF"]
FI_COLOR_BB = ALL_FI_COLORS[FISHERY_CODE == "BB"]
FI_COLOR_GI = ALL_FI_COLORS[FISHERY_CODE == "GN"][,   FISHERY_CODE := "GI"]
FI_COLOR_HD = ALL_FI_COLORS[FISHERY_CODE == "LIH"][,  FISHERY_CODE := "HD"]
FI_COLOR_TR = ALL_FI_COLORS[FISHERY_CODE == "LIT"][,  FISHERY_CODE := "TR"]
FI_COLOR_OT = ALL_FI_COLORS[FISHERY_CODE == "OT"]

FI_COLORS = FI_COLOR_FS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LS)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LF)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_BB)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_GI)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_HD)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_TR)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OT)