# FILTER THE DATASET ####

FL_YFT = copy(SF_STD_YFT)

## Iranian purse seiners ####
# No fishing mode available and huge variability in size histograms
#FL_YFT = FL_YFT[!(FLEET_CODE == "IRN" & FISHERY_GROUP_CODE == "PS")]

# 2- Remove EUREY and EUMYT HATR fisheries: mix of handlines and trolling lines?
#FL_YFT = FL_YFT[!(FLEET_CODE %in% c("EUREU", "EUMYT") & GEAR_CODE == "HATR")]

# SPATIAL RESOLUTION EQUAL OR LESS THAN 5x5 ####

# Filter resolution
FL_YFT_REGULAR_GRIDS = FL_YFT[AREA_TYPE_CODE %in% c("GRID01x01", "GRID05x05")]

# # Map to Indian Ocean 1x1 grids to filter for grids outside Indian Ocean 
IO_1x1_GRID_LIST = query(DB_IOTC_MASTER(), "SELECT DISTINCT CODE, NAME_EN FROM refs_gis.V_IO_GRIDS_01x01;")
# 
GRIDS_1x1_NOT_IN_IO = unique(merge(FL_YFT_REGULAR_GRIDS[AREA_TYPE_CODE == "GRID01x01"], IO_1x1_GRID_LIST, by.x = "FISHING_GROUND_CODE", by.y = "CODE", all.x = TRUE)[is.na(NAME_EN), .(FISHING_GROUND_CODE)])[order(FISHING_GROUND_CODE)]
 
GRIDS_1x1_NOT_IN_IO[, CWP55 := convert_CWP_grid(FISHING_GROUND_CODE, grid_5x5), by = .(FISHING_GROUND_CODE)]

# Remove these grids from the dataset prior to conversion
FL_YFT_REGULAR_GRIDS = FL_YFT_REGULAR_GRIDS[!FISHING_GROUND_CODE %in% GRIDS_1x1_NOT_IN_IO$FISHING_GROUND_CODE]

# Create original file for combination with irregular grid dataset
FL_YFT_REGULAR_GRIDS_ORIGINAL = FL_YFT_REGULAR_GRIDS[, .(FISH_COUNT = sum(FISH_COUNT)), keyby = .(YEAR, MONTH_START, MONTH_END, FLEET_CODE, GEAR_CODE, FISHERY_GROUP_CODE, FISHERY_TYPE_CODE, SCHOOL_TYPE_CODE, FISHERY_CODE, FISHING_GROUND_CODE, SPECIES_CODE, MEASURE_TYPE_CODE, CLASS_LOW, CLASS_HIGH, RAISE_CODE, REPORTING_QUALITY)]

# Convert 1x1 to 5x5
FL_YFT_REGULAR_GRIDS[AREA_TYPE_CODE == "GRID01x01", CWP55 := convert_CWP_grid(FISHING_GROUND_CODE, grid_5x5), by = .(FISHING_GROUND_CODE)]

# Keep 5x5 grids
FL_YFT_REGULAR_GRIDS[AREA_TYPE_CODE == "GRID05x05", CWP55 := FISHING_GROUND_CODE]

# Re-aggregate by 5x5 grids
FL_YFT_REGULAR_TO_CWP55 = FL_YFT_REGULAR_GRIDS[, .(FISH_COUNT = sum(FISH_COUNT)), keyby = .(YEAR, MONTH_START, MONTH_END, FLEET_CODE, GEAR_CODE, FISHERY_GROUP_CODE, FISHERY_TYPE_CODE, SCHOOL_TYPE_CODE, FISHERY_CODE, FISHING_GROUND_CODE = CWP55, SPECIES_CODE, MEASURE_TYPE_CODE, CLASS_LOW, CLASS_HIGH, RAISE_CODE, REPORTING_QUALITY)]

# DATASET WITH SPATIAL RESOLUTION LARGER THAN 5x5 SPATIAL RESOLUTION ####

# Extract area codes from dataset
LIST_NON_STANDARD_AREAS = FL_YFT[!AREA_TYPE_CODE %in% c("GRID01x01", "GRID05x05"), .(N_SAMPLES = sum(FISH_COUNT)), keyby = .(FISHING_GROUND_CODE, RAISE_CODE)][order(-N_SAMPLES)]

# Potential filter the list on non-standard areas
# Large areas of areas with too small samples (<50)
LIST_AREAS_TO_REMOVE = c("IO_EAST", "IO_NORTHEAST", "IO_NORTHWEST", "IO_SOUTHEAST", "IO_WEST", "IO_SOUTHWEST", "A230120", "A240140", "A240040")

# Summary of data removed
FL_YFT_IRREGULAR_GRIDS_REMOVED = FL_YFT[FISHING_GROUND_CODE %in% LIST_AREAS_TO_REMOVE, .(N_SAMPLES = sum(FISH_COUNT)), keyby = .(FISHING_GROUND_CODE, RAISE_CODE)]

LIST_NON_STANDARD_AREAS_FILTERED = LIST_NON_STANDARD_AREAS[!FISHING_GROUND_CODE %in% LIST_AREAS_TO_REMOVE]

# Extract mapping between irregular areas and 5x5 grids
MAPPING_NON_STANDARD_AREAS_TO_5x5 =
  query(
    C_MASTER, 
    paste0("SELECT SOURCE_CODE AS FISHING_GROUND_CODE, TARGET_CODE AS CWP55, SOURCE_REL_INTERSECTION
  FROM refs_gis.AREA_INTERSECTIONS
  WHERE SOURCE_CODE IN ('", paste(LIST_NON_STANDARD_AREAS_FILTERED$FISHING_GROUND_CODE, collapse = "', '"), "') 
  AND SUBSTRING(TARGET_CODE, 1, 1) = '6';"))

# Add number of 5x5 grids per irregular area
MAPPING_NON_STANDARD_AREAS_TO_5x5[, N_GRIDS := length(unique(CWP55)), keyby = .(FISHING_GROUND_CODE)]

MAPPING_NON_STANDARD_AREAS_TO_5x5[, PROP_GRIDS := 1/N_GRIDS]

# Map size dataset with 5x5 grids
FL_YFT_IRREGULAR_GRIDS = FL_YFT[FISHING_GROUND_CODE %in% LIST_NON_STANDARD_AREAS_FILTERED$FISHING_GROUND_CODE, .(FISH_COUNT = sum(FISH_COUNT)), keyby = .(YEAR, MONTH_START, MONTH_END, FLEET_CODE, GEAR_CODE, FISHERY_GROUP_CODE, FISHERY_TYPE_CODE, SCHOOL_TYPE_CODE, FISHERY_CODE, FISHING_GROUND_CODE, SPECIES_CODE, MEASURE_TYPE_CODE, CLASS_LOW, CLASS_HIGH, RAISE_CODE, REPORTING_QUALITY)]

FL_YFT_IRREGULAR_GRIDS_MAPPED_CWP55_GRID = merge.data.table(FL_YFT_IRREGULAR_GRIDS, MAPPING_NON_STANDARD_AREAS_TO_5x5, by.x = "FISHING_GROUND_CODE", by.y = "FISHING_GROUND_CODE", all.x = TRUE, allow.cartesian = TRUE)

# Distribute fish according to surface area
#FL_YFT_IRREGULAR_GRIDS_MAPPED_CWP55_GRID[, FISH_ALLOCATED := FISH_COUNT * SOURCE_REL_INTERSECTION, by = .(FISHING_GROUND_CODE)][, FISH_COUNT := NULL]

# Distribute fish evenly according to number of grids
FL_YFT_IRREGULAR_GRIDS_MAPPED_CWP55_GRID[, FISH_ALLOCATED := FISH_COUNT * PROP_GRIDS, by = .(FISHING_GROUND_CODE)][, FISH_COUNT := NULL]

# Rename FISH COUNT column
setnames(FL_YFT_IRREGULAR_GRIDS_MAPPED_CWP55_GRID, old = "FISH_ALLOCATED", new = "FISH_COUNT")

# Re-aggregate by 5x5 grids
FL_YFT_IRREGULAR_TO_CWP55 = FL_YFT_IRREGULAR_GRIDS_MAPPED_CWP55_GRID[, .(FISH_COUNT = sum(FISH_COUNT)), keyby = .(YEAR, MONTH_START, MONTH_END, FLEET_CODE, GEAR_CODE, FISHERY_GROUP_CODE, FISHERY_TYPE_CODE, SCHOOL_TYPE_CODE, FISHERY_CODE, FISHING_GROUND_CODE = CWP55, SPECIES_CODE, MEASURE_TYPE_CODE, CLASS_LOW, CLASS_HIGH, RAISE_CODE, REPORTING_QUALITY)]

# BUILD UNIFIED DATASETS

## ORIGINAL GRID DATASET ####
FL_YFT_ORIGINAL_GRIDS = rbindlist(list(FL_YFT_REGULAR_GRIDS_ORIGINAL, FL_YFT_IRREGULAR_GRIDS), use.names = TRUE)

## 5x5 GRID DATASET
FL_YFT_GRIDS_TO_CWP55 = rbindlist(list(FL_YFT_REGULAR_TO_CWP55, FL_YFT_IRREGULAR_TO_CWP55))

# Aggregate across 5x5 grids
FL_YFT_GRIDS_TO_CWP55 = FL_YFT_GRIDS_TO_CWP55[, .(FISH_COUNT = sum(FISH_COUNT)), keyby = .(YEAR, MONTH_START, MONTH_END, FLEET_CODE, GEAR_CODE, FISHERY_GROUP_CODE, FISHERY_TYPE_CODE, SCHOOL_TYPE_CODE, FISHERY_CODE, FISHING_GROUND_CODE, SPECIES_CODE, MEASURE_TYPE_CODE, CLASS_LOW, CLASS_HIGH, RAISE_CODE, REPORTING_QUALITY)]

# Export the datasets
write.csv(FL_YFT_ORIGINAL_GRIDS, paste0("../outputs/datasets/", DATASET_NAME, " (original).csv"), row.names = FALSE)
write.csv(FL_YFT_GRIDS_TO_CWP55, paste0("../outputs/datasets/", DATASET_NAME, " (cwp55).csv"), row.names = FALSE)

