# STOCK ASSESSMENT FISHERIES - AREA MAPPING



SA_FISHERY_AREAS_TABLE = fread("../inputs/mappings/FISHERY_AREA_MAPPINGS.csv")[, .(FISHERY, R1a, R1b, R2, R3, R4, R0)]

# IOTC FISHERIES - STOCK ASSESSMENT ASSESSMENT FISHERIES MAPPING ###
SA_FISHERY_MAPPING = fread("../inputs/mappings/FISHERY_AREA_MAPPINGS.csv")[, .(FLEET, GEAR_CODE, SCHOOL_TYPE_CODE, FISHERY)]

setnames(SA_FISHERY_MAPPING, new = c("FLEET_CODE", "GEAR_CODE", "CATCH_SCHOOL_TYPE_CODE", "SA_FISHERY_CODE"))

