# Color constants for current assessment areas

## Two areas model

SKJ_SA_AREA_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]  # IRALLIO or IRSKJWE
SKJ_SA_AREA_COLOR_2 = ALL_FI_COLORS[FISHERY_CODE == "BB"]    #            IRSKJEA

SA_AREA_COLORS_MULTIPLE = rbind(SKJ_SA_AREA_COLOR_1,
                                SKJ_SA_AREA_COLOR_2)

## One area model

SA_AREA_COLORS_SINGLE   = SKJ_SA_AREA_COLOR_1

# 

AR_COLORS = SA_AREA_COLORS_SINGLE #SA_AREA_COLORS_MULTIPLE # TO BE CHANGED IF THE SPATIAL MODEL CHANGES

# Color constants for original areas

AR_ORIG_COLORS = AR_COLORS

# Color constants for current fishery groups
                                                                   # Fishery
FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]                  # PS
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "BB"])  # PL
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "GN"])  # GL
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LIH"]) # LI
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"]) # LL
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])  # Other

# Color constants for current fisheries

FI_COLOR_PSFS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FI_COLOR_PSLS = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
FI_COLOR_PL   = ALL_FI_COLORS[FISHERY_CODE == "BB"]
FI_COLOR_GL   = ALL_FI_COLORS[FISHERY_CODE == "GN"]
FI_COLOR_LI   = ALL_FI_COLORS[FISHERY_CODE == "LIH"]
FI_COLOR_LL   = ALL_FI_COLORS[FISHERY_CODE == "LLD"]
FI_COLOR_OTHER= ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OTHER"]

FI_COLORS = FI_COLOR_PSFS                     # PSFS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PSLS)   # PSLS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PL)     # PL
FI_COLORS = rbind(FI_COLORS, FI_COLOR_GL)     # GL
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LI)     # LI
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL)     # LL
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OTHER)  # Other

FI_COLORS[FISHERY_CODE == "BB",    FISHERY_CODE := "PL"]
FI_COLORS[FISHERY_CODE == "GN",    FISHERY_CODE := "GL"]
FI_COLORS[FISHERY_CODE == "LIH",   FISHERY_CODE := "LI"]
FI_COLORS[FISHERY_CODE == "LLD",   FISHERY_CODE := "LL"]
FI_COLORS[FISHERY_CODE == "OTHER", FISHERY_CODE := "Other"]