# Issues to address in the database
## No gear code -- corresponds to EM for Spanish ELL -- remove the records
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & is.na(GEAR_CODE), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

#FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & is.na(GEAR_CODE), REPORTING_QUALITY := "6"]
#FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & is.na(GEAR_CODE), REPORTING_QUALITY := "6"]

FL_STD_DATA_SPECIES_TABLE_NO_GEAR = FL_STD_DATA_SPECIES_TABLE[is.na(GEAR_CODE)]
FL_STD_DATA_SPECIES_NO_GEAR       = FL_STD_DATA_SPECIES[is.na(GEAR_CODE)]

FL_STD_DATA_SPECIES_TABLE = FL_STD_DATA_SPECIES_TABLE[!is.na(GEAR_CODE)]
FL_STD_DATA_SPECIES       = FL_STD_DATA_SPECIES[!is.na(GEAR_CODE)]

## Unclassified gears
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & GEAR_CODE == "UNCL", .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & GEAR_CODE == "UNCL", REPORTING_QUALITY := "6"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & GEAR_CODE == "UNCL", REPORTING_QUALITY := "6"]

## Aggregate gears
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & GEAR_CODE %in% c("HATR", "G/L"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & GEAR_CODE %in% c("HATR", "G/L"), REPORTING_QUALITY := "4"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & GEAR_CODE %in% c("HATR", "G/L"), REPORTING_QUALITY := "4"]

## Seychelles semi-industrial longline fishery targeting swordfish
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "SYC" & GEAR_CODE %in% c("ELL"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "SYC" & GEAR_CODE %in% c("ELL"), REPORTING_QUALITY := "6"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & FLEET_CODE == "SYC" & GEAR_CODE %in% c("ELL"), REPORTING_QUALITY := "6"]

## NEIPS
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "NEIPS" & GEAR_CODE %in% c("PS"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "NEIPS" & GEAR_CODE %in% c("PS"), REPORTING_QUALITY := "0"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & FLEET_CODE == "NEIPS" & GEAR_CODE %in% c("PS"), REPORTING_QUALITY := "0"] 

## Deep-freezing longline fishery from South Africa
# 3 very small fish - not removed by the standardisation?
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "ZAF" & GEAR_CODE %in% c("LL"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "ZAF" & GEAR_CODE %in% c("LL"), REPORTING_QUALITY := "0"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & FLEET_CODE == "ZAF" & GEAR_CODE %in% c("LL"), REPORTING_QUALITY := "0"]

## Handline fishery from Tanzania
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "TZA" & GEAR_CODE %in% c("HAND"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "TZA" & GEAR_CODE %in% c("HAND"), REPORTING_QUALITY := "0"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & FLEET_CODE == "TZA" & GEAR_CODE %in% c("HAND"), REPORTING_QUALITY := "0"]

## Iranian Purse seiners
# School type is missing
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "IRN" & GEAR_CODE %in% c("PS"), .N, .(YEAR, FLEET_CODE, GEAR_CODE, FISHING_GROUND_CODE)]

FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY) & FLEET_CODE == "IRN" & GEAR_CODE %in% c("PS"), REPORTING_QUALITY := "4"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY) & FLEET_CODE == "IRN" & GEAR_CODE %in% c("PS"), REPORTING_QUALITY := "4"]

## Set all remaining records to good quality
## No apparent issue although difficult to assess when few records are available
FL_STD_DATA_SPECIES_TABLE[is.na(REPORTING_QUALITY), REPORTING_QUALITY := "0"]
FL_STD_DATA_SPECIES[is.na(REPORTING_QUALITY), REPORTING_QUALITY := "0"]