# Color constants for current assessment areas

AR_COLOR_NE = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
AR_COLOR_SE = ALL_FI_COLORS[FISHERY_CODE == "LLF"]
AR_COLOR_ES = ALL_FI_COLORS[FISHERY_CODE == "LLD"]
AR_COLOR_WS = ALL_FI_COLORS[FISHERY_CODE == "BB"]
AR_COLOR_SW = ALL_FI_COLORS[FISHERY_CODE == "BB"]
AR_COLOR_NW = ALL_FI_COLORS[FISHERY_CODE == "GN"]

AR_COLOR_WS$FILL = darken(AR_COLOR_WS$FILL, amount = 0.2)
AR_COLOR_WS$OUTLINE = darken(AR_COLOR_WS$OUTLINE, amount = 0.2)

AR_COLORS = AR_COLOR_NE
AR_COLORS = rbind(AR_COLORS, AR_COLOR_SE)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_ES)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_WS)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_SW)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_NW)

# Color constants for original areas

AR_ORIG_COLORS = AR_COLORS

# Color constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "GN"] # Swordfish longliners...
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLF"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])

# Color constants for current fisheries

#FI_COLOR_ALGI = ALL_FI_COLORS[FISHERY_CODE == "GN"]
#FI_COLOR_AUEL = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
#FI_COLOR_EUEL = ALL_FI_COLORS[FISHERY_CODE == "LLD"][, FISHERY_CODE := "LL"]
#FI_COLOR_ISEL = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "FL"]
#FI_COLOR_JPLL = ALL_FI_COLORS[FISHERY_CODE == "BB"]
#FI_COLOR_TWFL = ALL_FI_COLORS[FISHERY_CODE == "LIT"][, FISHERY_CODE := "LINE"]
#FI_COLOR_TWLL = ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OTHER"]

FI_COLORS = color_table(unique_colors(7))
FI_COLORS$FISHERY_CODE = c("ALGI", "AUEL", "EUEL", "ISEL", "JPLL", "TWFL", "TWLL") # Same as in 00.92.species_area_fishery.R which is invoked later... :|