# Colour constants for current assessment areas

AR_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
AR_COLOR_2 = ALL_FI_COLORS[FISHERY_CODE == "GN"]
AR_COLOR_3 = ALL_FI_COLORS[FISHERY_CODE == "LLD"]
AR_COLOR_4 = ALL_FI_COLORS[FISHERY_CODE == "LIH"]

AR_COLORS = AR_COLOR_1
AR_COLORS = rbind(AR_COLORS, AR_COLOR_2)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_3)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_4)

# Colour constants for original areas

AR_ORIG_COLORS = AR_COLORS

# Colour constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "GN"]
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLF"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "PSLS"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])

# Colour constants for current fisheries

FI_COLOR_DN3 = ALL_FI_COLORS[FISHERY_CODE == "GN"][, FISHERY_CODE := "DN3"]

FI_COLOR_DN4 = ALL_FI_COLORS[FISHERY_CODE == "GN"][, FISHERY_CODE := "DN4"]
FI_COLOR_DN4$FILL    = darken(FI_COLOR_DN4$FILL, 0.2)
FI_COLOR_DN4$OUTLINE = darken(FI_COLOR_DN4$OUTLINE, 0.2)

FI_COLOR_LL1 = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "LL1"]
FI_COLOR_LL2 = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "LL2"]
FI_COLOR_LL2$FILL    = darken(FI_COLOR_LL1$FILL, 0.2)
FI_COLOR_LL2$OUTLINE = darken(FI_COLOR_LL1$OUTLINE, 0.2)

FI_COLOR_LL3 = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "LL3"]
FI_COLOR_LL3$FILL    = darken(FI_COLOR_LL2$FILL, 0.2)
FI_COLOR_LL3$OUTLINE = darken(FI_COLOR_LL2$OUTLINE, 0.2)

FI_COLOR_LL4 = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "LL4"]
FI_COLOR_LL4$FILL    = darken(FI_COLOR_LL3$FILL, 0.2)
FI_COLOR_LL4$OUTLINE = darken(FI_COLOR_LL3$OUTLINE, 0.2)

FI_COLOR_PS1 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"][, FISHERY_CODE := "PS1"]

FI_COLOR_PS2 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"][, FISHERY_CODE := "PS2"]
FI_COLOR_PS2$FILL    = darken(FI_COLOR_PS1$FILL, 0.2)
FI_COLOR_PS2$OUTLINE = darken(FI_COLOR_PS1$OUTLINE, 0.2)

FI_COLOR_PS3 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"][, FISHERY_CODE := "PS3"]
FI_COLOR_PS3$FILL    = darken(FI_COLOR_PS2$FILL, 0.2)
FI_COLOR_PS3$OUTLINE = darken(FI_COLOR_PS2$OUTLINE, 0.2)

FI_COLOR_PS4 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"][, FISHERY_CODE := "PS4"]
FI_COLOR_PS4$FILL    = darken(FI_COLOR_PS3$FILL, 0.2)
FI_COLOR_PS4$OUTLINE = darken(FI_COLOR_PS3$OUTLINE, 0.2)

FI_COLOR_OT1  = ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OT1"]

FI_COLOR_OT2  = ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OT2"]
FI_COLOR_OT2$FILL    = darken(FI_COLOR_OT1$FILL, 0.2)
FI_COLOR_OT2$OUTLINE = darken(FI_COLOR_OT1$OUTLINE, 0.2)

FI_COLOR_OT3  = ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OT3"]
FI_COLOR_OT3$FILL    = darken(FI_COLOR_OT2$FILL, 0.2)
FI_COLOR_OT3$OUTLINE = darken(FI_COLOR_OT2$OUTLINE, 0.2)

FI_COLOR_OT4  = ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OT4"]
FI_COLOR_OT4$FILL    = darken(FI_COLOR_OT3$FILL, 0.2)
FI_COLOR_OT4$OUTLINE = darken(FI_COLOR_OT3$OUTLINE, 0.2)

FI_COLORS = FI_COLOR_DN3
FI_COLORS = rbind(FI_COLORS, FI_COLOR_DN4)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL1)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL2)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL3)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL4)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OT1)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OT2)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OT3)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OT4)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PS1)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PS2)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PS3)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PS4)